### ISSUE TITLE
Create endpoint to download latest nightly build

### ISSUE THREAD

**Issue by ianhi** [micro-manager/download-mm#2]
## Problem

Currently you can download the latest micromanager versions easily - but there doesn't seem to be an easy way to programmatically find the most recent nightly build because it requires knowing both the version numbre and the build information like so:

https://github.com/tlambert03/pymmcore-plus/blob/5de999d4967ff7f92bcc745a1d7f4a1fe591a73e/pymmcore_plus/install.py#L8-L15

then that needs to be regularly updated and is fragile w.r.t things like the naming scheme changing (e.g. from gamma -> 2.0.x broke that download).

## Potential Solution

Have two new endpoints `Windows/latest` and `Mac/latest` that are stable names and always download the  most recent nightly build.

**Comment by marktsuchida** [comment]
Now that we have a new download location, we can implement this!
https://download.micro-manager.org/latest-experimental/windows/MMSetup_x64_latest.exe
https://download.micro-manager.org/latest-experimental/macos/Micro-Manager-x86_64-latest.dmg

These links will redirect (302) to the latest development build (which currently is the latest nightly build). If clicked in a browser, they will save the file under its original name (i.e. with the date in the filename), but if you use `curl -LO` they will (by definition of the `-O`) use the fixed name in the URL (convenient for scripting).

Let me know if these satisfy your use case. If so, I'll remove the `-experimental` from the URLs.

**Comment by ianhi** [comment]
@marktsuchida this is awesome! The only other thing that miiiiight be nice is to have somewhere to query what the filename we'd be downloading is - in order to put it into an appropriately named folder. But either way I'd say you're good to remove the "experimental" thanks for this!

**Comment by marktsuchida** [comment]
@ianhi I removed the `-experimental`.
For getting the date-specific filename, `curl -JLO` ("use remote header name") works -- not sure what the equivalent would be using `urllib`, but I think it's possible.
